version: '3.8'
services:
  scrapy:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./webscraper:/app
    stdin_open: true
    tty: true
    working_dir: /app
    environment: 
      - INSTALL_REQUIREMENTS=true
